name: Test Composite Action

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run composite action
        id: my-action
        uses: ./.github/actions/my-composite-actions
        with:
          node-version: '18'

      - name: Display result
        run: |
          echo "Script Result: ${{ steps.my-action.outputs.script-result }}"
