name: Check PR Title Securely

on: [pull_request]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title securely
        uses: actions/github-script@v6
        with:
          script: |
            const title = '${{ github.event.pull_request.title }}';
            if (!title.startsWith('octocat')) {
              core.setFailed("PR title must start with 'octocat'");
            }
